# Motor
MOTOR_FL_PH, MOTOR_FL_PWM, MOTOR_FL_INVERT = "C29", "C28", True
MOTOR_FR_PH, MOTOR_FR_PWM, MOTOR_FR_INVERT = "C31", "C30", True
MOTOR_B_PH,  MOTOR_B_PWM,  MOTOR_B_INVERT  = "D5",  "D4",  False
# Encoder
ENC_FL_A, ENC_FL_B, ENC_FL_INVERT = "C0",  "C1",  False
ENC_FR_A, ENC_FR_B, ENC_FR_INVERT = "C2",  "C3",  False
ENC_B_A,  ENC_B_B,  ENC_B_INVERT  = "D13", "D14", True
# Keys & LEDs
BTN_EXIT_PIN, BTN_START_PIN, BTN_MODE_PIN = "C8", "C9", "C14"
LED_HB_PIN = "C4"
LED_STRAIGHT_PIN, LED_TRANSLATE_PIN, LED_ROTATE_PIN = "C19", "C20", "C21"
# PWM
MOTOR_FREQ     = 13000
PWM_MAX        = 60000
MOTOR_DUTY_MAX = 60000
MOTOR_DUTY_MIN = 300
# Control
TICK_PERIOD_MS    = 5
PWM_SMOOTH_FACTOR = 0.4
MAX_PWM_CHANGE    = 4800
# Camera UART
CAM_UART_ID   = 0
CAM_UART_BAUD = 9600
# Single-car task mode keeps coop files available but disables coop communication.
COOP_ROLE = "MASTER"
COOP_ENABLE = False
COOP_WIRELESS_BAUD = 460800
COOP_TX_PERIOD_MS = 80
MASTER_MOTION_TX_PERIOD_MS = 80
COOP_TARGET_REPEAT_MS = 120
COOP_READY_REPEAT_MS = 80
COOP_STOP_REPEAT_MS = 80
COOP_LINK_TIMEOUT_MS = 1200
COOP_MASTER_WAIT_SLAVE_MS = 8000
COOP_GUIDE_MM_PER_SPEED_UNIT_S = 50
COOP_SLAVE_APPROACH_SPEED = 4.0
COOP_SLAVE_APPROACH_MS = 1600
COOP_SLAVE_CLASSIFY_GRACE_MS = 400
COOP_SLAVE_HOLD_SPEED_BIAS = 0.8
# Vision navigation
NAV_LOW_SPD_TH  = 30
NAV_CORRECT_DIV = 6
