# Motor
MOTOR_FL_PH, MOTOR_FL_PWM, MOTOR_FL_INVERT = "C29", "C28", False
MOTOR_FR_PH, MOTOR_FR_PWM, MOTOR_FR_INVERT = "C31", "C30", False
MOTOR_B_PH,  MOTOR_B_PWM,  MOTOR_B_INVERT  = "D5",  "D4",  False
# Encoder
ENC_FL_PULSE, ENC_FL_DIR, ENC_FL_INVERT = "C0",  "C1",  False
ENC_FR_PULSE, ENC_FR_DIR, ENC_FR_INVERT = "C2",  "C3",  False
ENC_B_PULSE,  ENC_B_DIR,  ENC_B_INVERT  = "D13", "D14", False
ENC_SCALE = 0.05
# Keys & LEDs
BTN_EXIT_PIN, BTN_START_PIN, BTN_MODE_PIN = "C8", "C9", "C14"
LED_HB_PIN = "C4"
LED_STRAIGHT_PIN, LED_TRANSLATE_PIN, LED_ROTATE_PIN = "C19", "C20", "C21"
# PWM
MOTOR_FREQ     = 13000
PWM_MAX        = 60000
MOTOR_DUTY_MAX = 60000
MOTOR_DUTY_MIN = 300
# Control
TICK_PERIOD_MS    = 5
PWM_SMOOTH_FACTOR = 0.5
MAX_PWM_CHANGE    = 7200
# Camera UART
CAM_UART_ID   = 0
CAM_UART_BAUD = 9600
# Follower uses the SeekFree wireless UART to receive master motion feed.
COOP_WIRELESS_BAUD = 460800
# Vision navigation
NAV_LOW_SPD_TH  = 30
NAV_CORRECT_DIV = 6
