# Motor
MOTOR_FL_PH, MOTOR_FL_PWM, MOTOR_FL_INVERT = "C30", "C31", False
MOTOR_FR_PH, MOTOR_FR_PWM, MOTOR_FR_INVERT = "D4",  "D5",  False
MOTOR_B_PH,  MOTOR_B_PWM,  MOTOR_B_INVERT  = "C28", "C29", False
# Encoder
ENC_FL_A, ENC_FL_B, ENC_FL_INVERT = "C2",  "C3",  False
ENC_FR_A, ENC_FR_B, ENC_FR_INVERT = "D13", "D14", False
ENC_B_A,  ENC_B_B,  ENC_B_INVERT  = "C0",  "C1",  False
# Keys & LEDs
BTN_EXIT_PIN, BTN_START_PIN, BTN_MODE_PIN = "C8", "C9", "C14"
LED_HB_PIN = "C4"
LED_STRAIGHT_PIN, LED_TRANSLATE_PIN, LED_ROTATE_PIN = "C19", "C20", "C21"
# PWM
MOTOR_FREQ     = 13000
PWM_MAX        = 60000
MOTOR_DUTY_MAX = 60000
MOTOR_DUTY_MIN = 300
# Control
TICK_PERIOD_MS    = 5
PWM_SMOOTH_FACTOR = 0.4
MAX_PWM_CHANGE    = 4800
# Camera UART
CAM_UART_ID   = 0
CAM_UART_BAUD = 9600
# Vision navigation
NAV_LOW_SPD_TH  = 30
NAV_CORRECT_DIV = 6
